### PR TITLE
Fix: respect locked content when returning to location (fixes #51)

### LINKED ISSUE #51: Scroll to locked content if failing to restore to a point after locked content
https://github.com/adaptlearning/adapt-contrib-bookmarking/blob/acd8973ab061340cf173cc35fd2f2bb48d3309aa/js/adapt-contrib-bookmarking.js#L124

### PR DESCRIPTION
**Pull request by chris-steele**
#51 

### Fix
* respect locked content when returning to location

### Notes

If the bookmark is of type contentobject and the location is locked or preceded by locked content then the user is returned to the nearest unlocked contentobject prior to the location.

If the bookmark is of type article/block/component and the location is preceded by locked content then the user is returned to the nearest point prior to the location that is not itself preceded by locked content.

### CODE REVIEW

**Comment by chris-steele** [comment]
### Notes

If the bookmark is of type contentobject and the location is locked or preceded by locked content then the user is returned to the nearest unlocked contentobject prior to the location.

If the bookmark is of type article/block/component and the location is preceded by locked content then the user is returned to the nearest point prior to the location that is not itself preceded by locked content.

File: js/adapt-contrib-bookmarking.js [hunk 1]
```diff
@@ -171,13 +171,52 @@ class Bookmarking extends Backbone.Controller {
...
+
+      if (isPrecededByLockedContent) {
+        const nearestUnlockedIndex = precedingModels.reverse().findIndex(i => !i.get('_isLocked'));
+        target = precedingModels[nearestUnlockedIndex + 1].get('_id');
+      }
+    }
+
+    return target;
+  }
+
```
Comment (oliverfoster) [inline js/adapt-contrib-bookmarking.js]:
```suggestion
  /**
   * If the bookmark is preceded by locked content then find the nearest appropriate location
   * @param {string} id the bookmarked location
   * @returns the identifier of the location to return the user
   */
  resolveLocking(id) {
    const model = data.findById(id);

    const isCourse = model.isTypeGroup('course');
    if (isCourse) return id;

    const isContentObject = model.isTypeGroup('contentobject');
    // do not allow navigation to a locked page/menu
    const isLockedContentObject = isContentObject && model.get('_isLocked')

    // bookmark is by contentobject or article/block/component
    const descendants = isContentObject
      ? Adapt.course.getAllDescendantModels(true).filter(descendant => descendant.isTypeGroup('contentobject'))
      : model.findAncestor('page').getAllDescendantModels(true);
    
    const precedingModels = descendants.slice(0, descendants.indexOf(model));
    const isPrecededByLockedContent = precedingModels.some(precedingModel => precedingModel.get('_isLocked'));
    
    if (!isPrecededByLockedContent && !isLockedContentObject) return id;

    const offset = isContentObject ? 0 : 1;
    const nearestUnlockedIndex = precedingModels.reverse().findIndex(precedingModel => !precedingModel.get('_isLocked'));
    return precedingModels[nearestUnlockedIndex + offset].get('_id');
  }

```

* Single character variables changed for named variables. Single character names are short but not at all readable, `i` to `descendant` and `i` to `precedingModel`
* Removed nesting through return earlies and moving main function use-case to the bottom. Return original id on course, get descendants of type, check locking, return original id if not locked, return relevantly offset new location
* Reduced repetition by extracting processing variations into variables `decendants`, `offset`, `isLockedContentObject`, `isContentObject`
* Renamed function to better suit behaviour from `getAppropriateReturnPath` to more specific `resolveLocking`
* Changed `findAncestor('pages')` to `findAncestor('page')` as [`findAncestor` uses `isTypeGroup`](https://github.com/adaptlearning/adapt-contrib-core/blob/d1d4aae7bf2b2114629435a3136af7d571cf8a32/js/models/adaptModel.js#L401) which [takes singular types](https://github.com/adaptlearning/adapt-contrib-core/blob/d1d4aae7bf2b2114629435a3136af7d571cf8a32/js/models/adaptModel.js#L362) 

would you mind commenting on why offset is needed?

File: js/adapt-contrib-bookmarking.js [hunk 2]
```diff
@@ -171,13 +171,45 @@ class Bookmarking extends Backbone.Controller {
...
+    const nearestUnlockedIndex = precedingModels.reverse().findIndex(precedingModel => !precedingModel.get('_isLocked'));
+    return precedingModels[nearestUnlockedIndex + offset].get('_id');
+  }
+
   navigateTo(location = this.location) {
     const id = this.getLocationId(location);
     if (['', undefined, 'current'].includes(id)) return;
     _.defer(async () => {
       try {
+        const target = this.getAppropriateReturnPath(id);
```
Comment (oliverfoster) [inline js/adapt-contrib-bookmarking.js]:
```suggestion
        const target = this.resolveLocking(id);
```

**Review by oliverfoster — APPROVED** [review]

**Comment by oliverfoster** [comment]
Would you mind commenting on why `offset` is needed? @chris-steele

**Comment by chris-steele** [comment]
@oliverfoster sorry I misinterpreted the way trickle would lock - have removed offset

File: js/adapt-contrib-bookmarking.js [hunk 3]
```diff
@@ -171,13 +171,44 @@ class Bookmarking extends Backbone.Controller {
...
+      ? Adapt.course.getAllDescendantModels(true).filter(descendant => descendant.isTypeGroup('contentobject'))
+      : model.findAncestor('page').getAllDescendantModels(true);
+    
+    const precedingModels = descendants.slice(0, descendants.indexOf(model));
+    const isPrecededByLockedContent = precedingModels.some(precedingModel => precedingModel.get('_isLocked'));
+    
+    if (!isPrecededByLockedContent && !isLockedContentObject) return id;
+
+    const nearestUnlockedIndex = precedingModels.reverse().findIndex(precedingModel => !precedingModel.get('_isLocked'));
+    return precedingModels[nearestUnlockedIndex].get('_id');
```
Comment (oliverfoster) [inline js/adapt-contrib-bookmarking.js]: Are there any contrived conditions where this would be `undefined.get('id')`?

Line 205 does a soundness check on the original id, then this line recalculates the id after the check. Should `resolveLocking` perhaps fail nicely at 200, if no model is found, and be executed between 204 and 205 instead?

File: js/adapt-contrib-bookmarking.js [hunk 4]
```diff
@@ -171,15 +171,46 @@ class Bookmarking extends Backbone.Controller {
...
+
+    const nearestUnlockedIndex = precedingModels.reverse().findIndex(precedingModel => !precedingModel.get('_isLocked'));
+    return precedingModels[nearestUnlockedIndex]?.get('_id');
+  }
+
   navigateTo(location = this.location) {
     const id = this.getLocationId(location);
-    if (['', undefined, 'current'].includes(id)) return;
+    const target = this.resolveLocking(id);
+    if (['', undefined, 'current'].includes(target)) return;
```
Comment (oliverfoster) [inline js/adapt-contrib-bookmarking.js]:
```suggestion
    if (['', undefined, 'current'].includes(id)) return;
    const target = this.resolveLocking(id);
    if (!target) return;
```

Comment (chris-steele) [reply js/adapt-contrib-bookmarking.js]: Yes of course, sorry 👍

**Review by oliverfoster — APPROVED** [review]

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by lemmyadams — APPROVED** [review]

**Review by ethan-lp — APPROVED** [review]
