### PR TITLE
New: Furthest location & button features (fixes: #63)

### LINKED ISSUE #63: Feature - Allow furthest point of progress
### Subject of the issue/enhancement/features
Would like to introduce an option for bookmarking to allow learners to be taken to the furthest point of progress instead of their last known location.

### PR DESCRIPTION
**Pull request by joe-replin**
fixes #63 

### Delete
* Removes redundant return in navigateCancel function

### New
* Allows to set whether Bookmarking takes learners back to their last previously visited location or your furthest incomplete location with a new JSON field, "_location". The furthest option will pair best in a course with linear progression.
* Uses the new [DOM Element Modification API](https://github.com/adaptlearning/adapt-contrib-core/releases/tag/v6.38.0) to allow the inclusion of a unique element tag, `<bookmarking />`. This will add a button into any compiled JSON field. This button will always navigate learners to their furthest point of progression according to model data.
* The labels for the button will pull data from the following locations in this order: Button Attribute, Adapt Course Globals, Button Inner HTML

[//]: # (List appropriate steps for testing if needed)
### Testing
1. After installation, test both level settings "furthest" & "previous" while connected to an LMS. Ensure the bookmarking notify prompt is navigating you to the appropriate location.
2. Place the `<bookmarking />` tag in any compiled JSON field and test that it is taking you to your furthest point of progression.

### CODE REVIEW

**Comment by joe-replin** [comment]
@oliverfoster, I've left an empty model file as I assume we'll want to move much over from what is currently the controller file. I didn't want to do too much with this one ticket. Happy to take this whichever direction you think is best.

File: js/adapt-contrib-bookmarking.js [hunk 1]
```diff
@@ -194,6 +262,13 @@ class Bookmarking extends Backbone.Controller {
     if (highestOnscreenLocation) this.setLocationID(highestOnscreenLocation);
   }
 
+  checkFurthestIncompleteModel() {
```
Comment (oliverfoster) [inline js/adapt-contrib-bookmarking.js]:
```suggestion
  get furthestIncompleteModel() {
```

File: js/adapt-contrib-bookmarking.js [hunk 2]
```diff
@@ -109,6 +165,19 @@ class Bookmarking extends Backbone.Controller {
     this.stopListening(Adapt, 'bookmarking:cancel');
   }
 
+  navigateToFurthest() {
+    const furthestModel = this.checkFurthestIncompleteModel();
+    const furthestId = furthestModel.attributes._id;
```
Comment (oliverfoster) [inline js/adapt-contrib-bookmarking.js]:
```suggestion
    const furthestModel = this.furthestIncompleteModel;
    const furthestId = furthestModel.get('_id');
```
`model.attributes` is a private property in backbone and shouldn't be used directly

File: js/adapt-contrib-bookmarking.js [hunk 3]
```diff
@@ -97,6 +139,20 @@ class Bookmarking extends Backbone.Controller {
     });
   }
 
+  navigateTo() {
+    const locationConfig = this.config._location;
```
Comment (oliverfoster) [inline js/adapt-contrib-bookmarking.js]:
```suggestion
    const locationConfig = this.config._location || 'previous';
```
Default for backward compatibility.

File: js/adapt-contrib-bookmarking.js [hunk 4]
```diff
@@ -34,10 +50,36 @@ class Bookmarking extends Backbone.Controller {
...
+      'added:bookmarking': this.onAdd,
+      'removed:div.bookmarking': this.onRemove
     });
   }
 
+  onAdd(event) {
+    if (!this.isEnabled) return;
+    const $target = $(event.target);
+    const model = new BookmarkingModel({
+      label: $target.attr('label') || null,
```
Comment (oliverfoster) [inline js/adapt-contrib-bookmarking.js]: Will you ever need html in the label? If so:
```html
<bookmarking><span>some html</span></bookmarking>
```
Also needs to be support.

```suggestion
      label: $target.attr('label') || $target.html() || null,
```

**Review by oliverfoster — CHANGES_REQUESTED** [review]

File: js/adapt-contrib-bookmarking.js (hunk 1 above)
Comment (oliverfoster) [reply js/adapt-contrib-bookmarking.js]: This is a getter, it returns a model, check is kind of the wrong verb.

**Comment by oliverfoster** [comment]
Doesn't need to be breaking but the minimum fw is required.
Breaking is when this plugin doesn't support its old config or styling or apis.

**Comment by joe-replin** [comment]
Sage review, @oliverfoster, as always. Thank you.

File: templates/bookmarkingResume.jsx [hunk 5]
```diff
@@ -8,6 +8,7 @@ export default function Bookmarking(props) {
   return (
     <div className="bookmarking-resume__inner">
       <button
+        type='button'
```
Comment (oliverfoster) [inline templates/bookmarkingResume.jsx:13]: Why `type="button"` on a `button`?

In the spec `type="button"` does nothing relative to forms:
https://html.spec.whatwg.org/multipage/form-elements.html#attr-button-type

Does this prevent the button submitting forms if injected inside a form?

File: js/adapt-contrib-bookmarking.js [hunk 6]
```diff
@@ -5,6 +5,14 @@ import location from 'core/js/location';
 import router from 'core/js/router';
 import notify from 'core/js/notify';
 import data from 'core/js/data';
+import BookmarkingModel from './BookmarkingModel';
+import BookmarkingView from './BookmarkingView';
+import documentModifications from 'core/js/DOMElementModifications';
+
+// Allow self-closing <bookmarking-resume /> in any compiled json attribute, displayTitle, body, instruction, etc
```
Comment (oliverfoster) [inline js/adapt-contrib-bookmarking.js:12]:
```suggestion
// Allow self-closing <bookmarking /> in any compiled json attribute, displayTitle, body, instruction, etc
```

File: templates/bookmarkingResume.jsx (hunk 5 above)
Comment (joe-replin) [reply templates/bookmarkingResume.jsx:13]: Decision was made after reading MDN doc. See Note 3: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#notes

Comment (oliverfoster) [reply templates/bookmarkingResume.jsx:13]: I see. It would only be an issue if injected into a form. Fair enough.

File: js/BookmarkingModel.js [hunk 7]
```diff
@@ -0,0 +1,3 @@
+export default class BookmarkingModel extends Backbone.Model {
+
```
Comment (oliverfoster) [inline js/BookmarkingModel.js:2]: did you want to add aria label and label defaults?

```suggestion

  defaults () {
    return {
      label: '',
      ariaLabel: ''
    };
  }

```

Comment (joe-replin) [reply js/BookmarkingModel.js:2]: Agreed. Do you suppose it might be better to link this to either a new "_button" or "_global" set of fields in course.json?

Comment (oliverfoster) [reply js/BookmarkingModel.js:2]: Yes, good plan, globals is good.

Comment (joe-replin) [reply js/BookmarkingModel.js:2]: I will make an alternate ticket to change the core schemas. But adding this in as well.

**Comment by joe-replin** [comment]
~~Added PR to include Bookmarking Resume button labels in core.
https://github.com/adaptlearning/adapt-contrib-core/pull/447~~

**Comment by joe-replin** [comment]
Closed [CORE PR](https://github.com/adaptlearning/adapt-contrib-core/pull/447) in favor of placing labels within the bookmarking schemas.

File: js/adapt-contrib-bookmarking.js [hunk 8]
```diff
@@ -34,10 +54,38 @@ class Bookmarking extends Backbone.Controller {
...
+      'added:bookmarking': this.onAdd,
+      'removed:div.bookmarking': this.onRemove
     });
   }
 
+  onAdd(event) {
+    if (!this.isEnabled) return;
+    const resumeLabel = this.globals._extensions._bookmarking.resumeButtonLabel;
+    const resumeAria = this.globals._extensions._bookmarking.resumeButtonAriaLabel;
+    console.log(resumeLabel, resumeAria);
```
Comment (oliverfoster) [inline js/adapt-contrib-bookmarking.js]:
```suggestion
```

File: js/adapt-contrib-bookmarking.js [hunk 9]
```diff
@@ -34,10 +54,37 @@ class Bookmarking extends Backbone.Controller {
...
+      'added:bookmarking': this.onAdd,
+      'removed:div.bookmarking': this.onRemove
     });
   }
 
+  onAdd(event) {
+    if (!this.isEnabled) return;
+    const resumeLabel = this.globals._extensions._bookmarking.resumeButtonLabel;
+    const resumeAria = this.globals._extensions._bookmarking.resumeButtonAriaLabel;
+    const $target = $(event.target);//
```
Comment (oliverfoster) [inline js/adapt-contrib-bookmarking.js]:
```suggestion
    const $target = $(event.target);
```

File: js/adapt-contrib-bookmarking.js [hunk 10]
```diff
@@ -109,6 +170,19 @@ class Bookmarking extends Backbone.Controller {
     this.stopListening(Adapt, 'bookmarking:cancel');
   }
 
+  navigateToFurthest() {
```
Comment (oliverfoster) [inline js/adapt-contrib-bookmarking.js]: `navigateToFurthest` and `navigateToPrevious` are effectively the same function, their only difference is to choose the `this.furthestIncompleteModel.get('id')` or `this.restoredLocationID`, the code from both functions could be moved into `navigateTo` and look something like this:

```js
  navigateTo() {
    const navigateToId = this.navigateToId;
    _.defer(async () => {
      try {
        const isSinglePage = (Adapt.contentObjects.models.length === 1);
        await router.navigateToElement(navigateToId, { trigger: true, replace: isSinglePage, duration: 400 });
      } catch (err) {
        logging.warn(`Bookmarking cannot navigate to id: ${navigateToId}\n`, err);
      }
    });
    this.stopListening(Adapt, 'bookmarking:cancel');
  }
  
  get navigateToId() {
    const locationConfig = this.config._location || 'previous';
    const navigateToId = (locationConfig === 'furthest')
      ? this.furthestIncompleteModel.get('_id')
      : this.restoredLocationID;
    return navigateToId;
  }
```

It is essential that both functions perform `this.stopListening(Adapt, 'bookmarking:cancel');`.

File: js/adapt-contrib-bookmarking.js (hunk 3 above)
Comment (oliverfoster) [reply js/adapt-contrib-bookmarking.js]: This default is missing and is required for backward compatibility.

File: js/adapt-contrib-bookmarking.js [hunk 11]
```diff
@@ -34,10 +54,37 @@ class Bookmarking extends Backbone.Controller {
       'menuView:ready': this.setupMenu,
       'pageView:preRender': this.setupPage,
       'view:childAdded': this.onChildViewAdded,
-      'view:preRemove': this.onChildViewPreRemove
+      'view:preRemove': this.onChildViewPreRemove,
+      'bookmarking:resume': this.navigateToFurthest
```
Comment (oliverfoster) [inline js/adapt-contrib-bookmarking.js]: This event handler is not correct.
```suggestion
      'bookmarking:resume': this.navigateTo
```

File: js/adapt-contrib-bookmarking.js [hunk 12]
```diff
@@ -49,7 +96,7 @@ class Bookmarking extends Backbone.Controller {
     _.delay(() => {
       if (this.isAlreadyOnScreen(this.restoredLocationID)) return;
       if (Adapt.course.get('_bookmarking')._showPrompt === false) {
-        this.navigateToPrevious();
+        this.navigateTo();
```
Comment (oliverfoster) [inline js/adapt-contrib-bookmarking.js:127]: It's not currently possible to disable the popup and instead have a resume button on the menu, without performing an immediate `navigateTo`. We probably need a `_shouldAlwaysResume = true` option, such that we can enable/disable that resume by default behaviour.

File: js/adapt-contrib-bookmarking.js [hunk 13]
```diff
@@ -109,6 +170,19 @@ class Bookmarking extends Backbone.Controller {
     this.stopListening(Adapt, 'bookmarking:cancel');
   }
 
+  navigateToFurthest() {
+    const furthestModel = this.furthestIncompleteModel;
+    const furthestId = furthestModel.get('_id');
```
Comment (oliverfoster) [inline js/adapt-contrib-bookmarking.js]: If all of the models are `_isComplete = true` I expect that `furthestIncompleteModel` will return `undefined` causing line 175 to produce a `cannot get on undefined` error. This highlights that the use-case where someone clicks `Resume` when a course is complete will need some more work.

Perhaps the button should be disabled if there's no furthest or previous place to resume to? And/or the resume id calculation should change over to `previous` if `furthest` isn't productive?

**Review by oliverfoster — CHANGES_REQUESTED** [review]

File: properties.schema [hunk 14]
```diff
@@ -3,6 +3,26 @@
   "$schema": "http://json-schema.org/draft-04/schema",
   "id": "http://jsonschema.net",
   "required": false,
+  "globals": {
+    "resumeButtonLabel": {
```
Comment (oliverfoster) [inline properties.schema]: I think we normally call these button text rather than button label.

File: properties.schema [hunk 15]
```diff
@@ -3,6 +3,26 @@
...
+      "type": "string",
+      "required": true,
+      "default": "Resume",
+      "inputType": "Text",
+      "validators": [],
+      "translatable": true,
+      "help": "Label for ubiquitous resume button."
```
Comment (oliverfoster) [inline properties.schema]: Help text isn't necessary here. Use of the word ubiquitous is perhaps a little much for non-English speakers.
```suggestion
```

File: properties.schema [hunk 16]
```diff
@@ -3,6 +3,26 @@
...
+    },
+    "resumeButtonAriaLabel": {
+      "type": "string",
+      "required": true,
+      "default": "Navigate to your furthest point of progress.",
+      "inputType": "Text",
+      "validators": [],
+      "translatable": true,
+      "help": "ARIA label for ubiquitous resume button."
```
Comment (oliverfoster) [inline properties.schema]: Help text isn't necessary here. Use of the word ubiquitous is perhaps a little much for non-English speakers.
```suggestion
```

File: schema/course.schema.json [hunk 17]
```diff
@@ -8,6 +8,43 @@
...
+              "properties": {
+                "_bookmarking": {
+                  "type": "object",
+                  "title": "Bookmarking",
+                  "default": {},
+                  "properties": {
+                    "resumeButtonLabel": {
+                      "type": "string",
+                      "title": "Resume button label",
+                      "description": "Label for ubiquitous resume button.",
```
Comment (oliverfoster) [inline schema/course.schema.json]: Description text isn't necessary here. Use of the word ubiquitous is perhaps a little much for non-English speakers.
```suggestion
```

File: schema/course.schema.json [hunk 18]
```diff
@@ -8,6 +8,43 @@
...
+                      "default": "Resume",
+                      "_adapt": {
+                        "translatable": true
+                      }
+                    },
+                    "resumeButtonAriaLabel": {
+                      "type": "string",
+                      "title": "Resume ARIA label",
+                      "description": "ARIA label for ubiquitous resume button.",
```
Comment (oliverfoster) [inline schema/course.schema.json]: Description text isn't necessary here. Use of the word ubiquitous is perhaps a little much for non-English speakers.
```suggestion
```

**Review by oliverfoster — CHANGES_REQUESTED** [review]

File: js/adapt-contrib-bookmarking.js (hunk 10 above)
Comment (joe-replin) [reply js/adapt-contrib-bookmarking.js]: Makes total sense to gain this efficiency, thank you.

File: js/adapt-contrib-bookmarking.js (hunk 12 above)
Comment (joe-replin) [reply js/adapt-contrib-bookmarking.js:127]: The button is there as a supplementary feature and not as a mandatory click for bookmarking. And it is up to the design to add the button or not.

I don't see a problem with the current implementation. If it is specifically decided to remove the popup on course load, the course will still follow the prescribed settings to navigate to the previous or furthest point, even if a button exists.

File: js/adapt-contrib-bookmarking.js (hunk 13 above)
Comment (joe-replin) [reply js/adapt-contrib-bookmarking.js]: Yes, we did accommodate for this before by removing the button altogether. I think that should maybe apply here as well. The problem is, the button will not function if the navigation is set to previous, as the currently location will usually be set to the resume button you are currently looking at. So it makes sense to prevent the addition of the resume button if:
1. the course is set to 'previous'
2. there are no more incomplete models

File: properties.schema (hunk 14 above)
Comment (joe-replin) [reply properties.schema]: Will apply

File: js/adapt-contrib-bookmarking.js (hunk 12 above)
Comment (oliverfoster) [reply js/adapt-contrib-bookmarking.js:127]: Yea, it's just a use case which feels relatively intuitive to me.

I have a feeling it'd be nicer to land on the menu and be able to optionally resume rather than just to jumping straight in. This is effectively what the popup allows you to do, either resume or dismiss. It would be nice to have that similar flow without the popup. I imagine the resume button to be used most often on a menu.

File: js/adapt-contrib-bookmarking.js (hunk 13 above)
Comment (oliverfoster) [reply js/adapt-contrib-bookmarking.js]: Cool. 

Can we make it disabled instead of removing it? Removing UI is probably not good general accessibility or design practice. 

The previous location will still change when navigating a completed revisited course, I don't see how the previous location would usually or always be at the resume button. Either way the button should probably be disabled if it is to resume at itself. Hmm..

File: js/adapt-contrib-bookmarking.js [hunk 19]
```diff
@@ -15,6 +23,33 @@ class Bookmarking extends Backbone.Controller {
...
+  }
+
+  get isEnabled() {
+    return Boolean(this.config?._isEnabled);
+  }
+
+  get navigateToId() {
+    const locationConfig = this.config._location || 'previous';
+    const navigateToId = (locationConfig === 'furthest')
+      ? this.furthestIncompleteModel.get('_id')
```
Comment (oliverfoster) [inline js/adapt-contrib-bookmarking.js]: If all models are `_isComplete: true` then this line will give a `cannot look up property get on undefined` error. Just need to work that out and decide what happens in `navigateTo`, when set to `furthest` as a consequence.

**Review by oliverfoster — CHANGES_REQUESTED** [review]

File: js/adapt-contrib-bookmarking.js (hunk 19 above)
Comment (joe-replin) [reply js/adapt-contrib-bookmarking.js]: Aye. In our project work, we removed the button in this case. I suppose we would follow our rules and disable the button in this case.

And thinking further, we are disabling these buttons in varied cases. Do you suppose it best to build in some console warnings depending on the situation?

**Comment by joe-replin** [comment]
Addressing requested changes.
1.	Always render the button - _Done_
2.	Always have the button resume to the furthest location - _Done. If location is set to previous, the button will always be disabled._
3.	Disable the button when no furthest location is available - _Done_
4.	Disable the button when the furthest location is on-screen - _Not Done. Is there an Adapt helper function that would assist here? I imagine it would need to measure when the button is inview while scrolling._
5.	Auto-route only when resume method is set to previous or provide an option to enable/disable auto-route. _Possible I'm not understanding. If location is set to 'furthest' and a prompt is not being shown, why is auto-routing to the furthest location a negative?_

File: js/adapt-contrib-bookmarking.js (hunk 13 above)
Comment (joe-replin) [reply js/adapt-contrib-bookmarking.js]: Addressed!

**Comment by joe-replin** [comment]
@oliverfoster, requesting your review of my edits and questions above.

**Review by oliverfoster — APPROVED** [review]

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by chris-steele — APPROVED** [review]
